@extends('layouts.app')

@section('content')
    <main class="main">
        <section class="error-section d-flex align-items-center justify-content-center min-vh-100">
            <div class="container text-center">
                <img src="{{ asset('errors/message.svg') }}" alt="Error" class="img-fluid mb-4" style="max-width: 300px;">
                <h4 class="mb-3 fw-bold">{{ $error ?? 'Something Went Wrong' }}</h4>
                <p class="sf-11">
                    @if ($error === 'Invalid credentials or inactive account.')
                        The username or password you entered is incorrect, or your account is not active. Please try again
                        or contact support.
                    @elseif($error === 'Account is temporarily locked. Try again later.')
                        Your account is locked due to multiple failed login attempts. Please wait 15 minutes before trying
                        again.
                    @elseif($error === 'Verification email sent. Please verify your email to proceed.')
                        A verification email has been sent to your email address. Please check your inbox (and spam folder)
                        to verify your email.
                    @elseif($error === 'Two-factor authentication required.')
                        Please enter the two-factor authentication code sent to your email or generated by your
                        authenticator app.
                    @elseif($error === 'Invalid social login provider.')
                        The selected social login provider is not supported. Please use a valid provider (Google, Facebook,
                        GitHub, Twitter).
                    @elseif(str_contains($error, 'Social login not enabled for'))
                        The social login provider is not enabled for your account. Please enable it in your profile settings
                        or use another login method.
                    @elseif($error === 'Social registration is disabled. Please use an existing account.')
                        New account registration via social login is disabled. Please log in with an existing account or
                        contact support.
                    @elseif($error === 'Account is not active.')
                        Your account is not active. Please contact support to reactivate your account.
                    @elseif($error === 'Maximum login limit exceeded.')
                        You have reached the maximum number of active sessions. Please log out from other devices or contact
                        support.
                    @elseif($error === 'User not authenticated.')
                        You must be logged in to access this page. Please log in and try again.
                    @elseif($error === 'User data not found.')
                        Your user data could not be found. Please contact support for assistance.
                    @elseif($error === 'Invalid or expired two-factor code.')
                        The two-factor authentication code you entered is invalid or has expired. Please try again.
                    @elseif($error === 'Invalid two-factor code or recovery code.')
                        The two-factor authentication code or recovery code you entered is invalid. Please try again.
                    @elseif($error === 'Invalid session. Please log in again.')
                        Your session is invalid. Please log in again to continue.
                    @else
                        An unexpected error occurred. Please try again later or contact support for assistance.
                    @endif
                </p>

                @if (isset($redirect))
                    {{-- Redirect button with loading text --}}
                    <a href="{{ $redirect }}" class="btn btn-sm btn-primary mt-3 px-4 rounded-pill"
                        data-loading-text="Continuing...">
                        Continue
                    </a>
                @else
                    {{-- Homepage button --}}
                    <a href="{{ url()->previous() }}" class="btn btn-sm btn-primary me-2 mt-3 px-4 rounded-pill"
                        data-loading-text="Taking you back...">
                        Go Back
                    </a>

                    {{-- Login button --}}
                    <a href="{{ url('/login') }}" class="btn btn-sm btn-outline-secondary mt-3 px-4 rounded-pill"
                        data-loading-text="Opening login page...">
                        Go to Login
                    </a>
                @endif
            </div>
        </section>
    </main>
@endsection
